# 토픽1. 데이터 사이언스 시작하기

## Numpy

### 02. numpy array의 생김새

In [1]:
import numpy

In [4]:
array1 = numpy.array([2, 3, 5, 7, 11, 13])
array1

array([ 2,  3,  5,  7, 11, 13])

In [5]:
type(array1)

numpy.ndarray

In [7]:
array1.shape

(6,)

In [9]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
array2.shape

(3, 4)

In [11]:
array1.size

6

In [12]:
array2.size

12

### 03. numpy array를 만드는 다양한 방법

#### 파이썬 리스트를 통해 생성

In [13]:
array1 = numpy.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])
print(array1)

[ 2  3  5  7 11 13 17 19 23 29 31]


#### 균일한 값으로 생성

In [15]:
array1 = numpy.full(6, 7)
print(array1)

[7 7 7 7 7 7]


In [16]:
# 모든 값이 0인 numpy array 생성
array1 = numpy.full(6, 0)
array2 = numpy.zeros(6, dtype = int)

print(array1)
print()
print(array2)

[0 0 0 0 0 0]

[0 0 0 0 0 0]


In [17]:
# 모든 값이 1인 numpy array 생성
array1 = numpy.full(6, 1)
array2 = numpy.ones(6, dtype = int)

print(array1)
print()
print(array2)

[1 1 1 1 1 1]

[1 1 1 1 1 1]


#### 랜덤한 값들로 생성

In [18]:
array1 = numpy.random.random(6)
print(array1)

[0.38820586 0.62655168 0.89759711 0.35716088 0.98061968 0.50513211]


#### 연속된 값들이 담긴 numpy array 생성

In [22]:
array1 = numpy.arange(3, 17, 3)
print(array1)

[ 3  6  9 12 15]


### 04. 모듈 별명 지어주기

In [23]:
import numpy as np

### 07. 인덱싱, 슬라이싱

In [24]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [26]:
array1[2]

5

In [27]:
array1[-1]

31

In [29]:
array1[[1, 3, 4]]

array([ 3,  7, 11])

In [33]:
array2 = np.array([2, 1, 3])
array1[array2]

array([5, 3, 7])

In [35]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [36]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [37]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [39]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

### 08. numpy 기본 연산

In [40]:
array1 = np.arange(10)
array2 = np.arange(10, 20)
print(array1)
print()
print(array2)

[0 1 2 3 4 5 6 7 8 9]

[10 11 12 13 14 15 16 17 18 19]


In [44]:
array1 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### 11. numpy 불린 연산

In [46]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [47]:
array1>4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [56]:
booleans = np.array([True, False, True])

In [57]:
np.where(booleans)

(array([0, 2], dtype=int64),)

In [54]:
filter =np.where(array1 > 4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [55]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])